blog/urls.py
from django.urls import path, register_converter
from . import views

app_name = 'blog'

urlpatterns = [

    path('', views.IndexView.as_view(), name='index'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('signup_done/', views.SignupDoneView.as_view(), name='signup_done'),
    path('signup_complete/<token>/', views.SignupCompleteView.as_view(), name='signup_complete'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('mypage/', views.MyPageView.as_view(), name='mypage'),
    path('mypage/create_post/', views.CreatePostView.as_view(), name='create_post'),
    # path('mypage/create_post_test/', views.CreatePostTestView.as_view(), name='create_post_test'),
    path('mypage/account_detail/<int:pk>/', views.AccountDetailView.as_view(), name='account_detail'),
    path('mypage/update_account/<int:pk>/', views.UpdateAccountView.as_view(), name='update_account'),
    path('mypage/blog_management/<int:pk>/', views.BlogManagementView.as_view(), name='blog_management'),
    path('mypage/blog_management/<int:pk>/update_blog_title/', views.UpdateBlogTitleView.as_view(), name='update_blog_title'),
    path('mypage/blog_management/<int:pk>/update_blog_url/', views.UpdateBlogUrlView.as_view(), name='update_blog_url'),
    path('mypage/blog_management/<int:pk>/update_blog_info_all/', views.UpdateBlogInfoAllView.as_view(), name='update_blog_info_all'),
    path('comment_post/', views.CommentPostView.as_view(), name='comment_post'),
    path('search/', views.SearchResultView.as_view(), name='search_result'),
    path('mypage/create_post/add_tag/', views.AddTagView.as_view(), name='add_tag'),
    path('mypage/create_post/add_category/', views.AddCategoryView.as_view(), name='add_category'),
    path('mypage/account_detail/<int:pk>/update_account_all/', views.UpdateAccountAllView.as_view(), name='update_account_all'),
    path('mypage/account_detail/<int:pk>/update_username/', views.UpdateUsernameView.as_view(), name='update_username'),
    path('mypage/account_detail/<int:pk>/update_email/', views.UpdateEmailView.as_view(), name='update_email'),
    path('mypage/account_detail/<int:pk>/update_password/', views.UpdatePasswordView.as_view(), name='update_password'),
    path('mypage/edit_contents_list/', views.EditContentsListView.as_view(), name='edit_contents_list'),
    path('mypage/edit_content/<str:pk>/', views.EditContentView.as_view(),name='edit_content'),
    path('mypage/edit_content/<str:pk>/add_category/', views.AddCategoryView.as_view(),name='add_category'),
    path('mypage/edit_content/<str:pk>/add_tag/', views.AddTagView.as_view(),name='add_tag'),
    path('mypage/edit_contents_list/delete_content/', views.DeleteContentView.as_view(),name='delete_content'),
    path('mypage/comments_list/', views.CommentsListView.as_view(),name='comments_list'),
    path('mypage/comments_list/update_comments_list/', views.UpdateCommentsListView.as_view(),name='update_comments_list'),
    path('mypage/design_customize/', views.DesignCustomizeView.as_view(),name='design_customize'),
    path('mypage/access_analytics/', views.AccessAnalyticsView.as_view(), name='access_analytics'),
    # path('cotegory_list/(?P<category>\w+)/', views.CategoryListView.as_view(), name='category_list'),
    path('cotegory_list/<str>/', views.CategoryListView.as_view(), name='category_list'),
    path('tags_list/<str>/', views.TagsListView.as_view(), name='tags_list'),
]

coopy/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('', include('userblog.urls')),
    # path('markdownx/', include('markdownx.urls') ),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/include/footer.html
<footer id="footer" class="text-right">
	<small class="p-3">&copy;coopy All rights reserved</small>
</footer>

templates/include/header-2.html
{% load static %}

<!-- ユーザー情報入力関連用ヘッダー -->
<header class="container-fluid">
	<div class="row header_wrap d-flex">
		<h1 class="logo col-12 d-flex">
			<a href="{% url 'blog:index' %}"><img src="{% static 'img/Coopy_LOGO.png' %}" alt="blog_logo" class="logo_image"></a>
		</h1>
	</div>
</header>

templates/include/header-3.html
{% load static %}

<!-- mypage関連用ヘッダー -->
<header class="container-fluid mypage_header">
	<div class="row header_wrap d-flex">
		<h1 class="logo col-4 text-left">
			<a href="{% url 'blog:index' %}"><img src="{% static 'img/Coopy_LOGO.png' %}" alt="blog_logo" class="logo_image"></a>
		</h1>
		<!-- ユーザー認証済:true -->
		{% if user.is_authenticated %}
			<div class="col-8 mt-3">
				<div class="container">
					<div class="row">

						<div class="col-5 offset-6">
							<a class="login_username" href="{% url 'blog:mypage' %}">{{ user.username }}</a>
						</div>
						<div class="humbergermenu_wrap col-1">
							<button id="open_btn" type="button" name="button"><i class="fas fa-bars open_btn_icon"></i></button>
							<div id="nav_contents">
								<button id="close_btn" type="button" name="button"><i class="fas fa-times close_btn_icon"></i></button>
								<ul class="humbergermenu_contents text-left mt-5">
									<li class="humbergermenu_contents_list"><a href="{% url 'blog:mypage' %}">マイページ</a></li>
									<li class="humbergermenu_contents_list"><a href="{% url 'blog:create_post' %}">記事投稿</a></li>
									<li class="humbergermenu_contents_list"><a href="{% url 'blog:edit_contents_list' %}">記事管理</a></li>
									<li class="humbergermenu_contents_list"><a href="{% url 'blog:comments_list' %}">コメント</a></li>
									<li class="humbergermenu_contents_list"><a href="{% url 'blog:account_detail' user.pk %}">アカウント管理</a></li>
									<li class="humbergermenu_contents_list"><a href="#">ヘルプ</a></li>
									<li class="humbergermenu_contents_list"><a href="{% url 'blog:logout' %}">ログアウト</a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		{% else %}
			<div class="col-5 offset-3 mt-3">
				<div class="container">
					<div class="row">
						<div class="menu_wrap col-8">
							<form method="get" action="{% url 'blog:search_result' %}" class="post_search_form">
								{% for field in post_search_form %}
									{{ field }}
								{% endfor %}
								<button type="submit" class="post_search_button"><i class="fas fa-search"></i></button>
							</form>
						</div>
						<div class="col-4">
							<div class="container">
								<div class="row">
									<ul>
										<li class="col-6 menu_list"><a href="{% url 'blog:login' %}">Login</a></li>
										<li class="col-6 menu_list"><a href="{% url 'blog:signup' %}">Signup</a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		{% endif %}
	</div>
</header>

templates/include/header.html
{% load static %}
<header class="container-fluid">
	<div class="row header_wrap d-flex">
		<h1 class="logo col-4 text-left">
			<a href="{% url 'blog:index' %}"><img src="{% static 'img/Coopy_LOGO.png' %}" alt="blog_logo" class="logo_image"></a>
		</h1>
		<!-- ユーザー認証済:true -->
		{% if user.is_authenticated %}
			<div class="col-8">
				<div class="container">
					<div class="row">
						<div class="menu_wrap col-6">
							{% url 'blog:create_post' as create_post %}
							{% url 'blog:mypage' as mypage %}
							{% url 'blog:edit_content' post.pk as edit_content %}
							{% ifnotequal request.path create_post %}
							{% ifnotequal request.path mypage %}
							{% ifnotequal request.path edit_content %}
							<form method="get" action="{% url 'blog:search_result' %}" class="post_search_form">
								{% for field in post_search_form %}
									{{ field }}
								{% endfor %}
								<button type="submit" class="post_search_button"><i class="fas fa-search"></i></button>
							</form>
							{% endifnotequal %}
							{% endifnotequal %}
							{% endifnotequal %}
						</div>
						<div class="col-5">
							<a class="login_username" href="{% url 'blog:mypage' %}">{{ user.username }}</a>
						</div>
						<div class="humbergermenu_wrap col-1">
							<button id="open_btn" type="button" name="button"><i class="fas fa-bars open_btn_icon"></i></button>
							<div id="nav_contents">
								<button id="close_btn" type="button" name="button"><i class="fas fa-times close_btn_icon"></i></button>
								<ul class="humbergermenu_contents text-left mt-5">
									<li class="humbergermenu_contents_list"><a href="{% url 'blog:mypage' %}">マイページ</a></li>
									<li class="humbergermenu_contents_list"><a href="{% url 'blog:create_post' %}">記事投稿</a></li>
									<li class="humbergermenu_contents_list"><a href="{% url 'blog:edit_contents_list' %}">記事管理</a></li>
									<li class="humbergermenu_contents_list"><a href="{% url 'blog:comments_list' %}">コメント</a></li>
									<li class="humbergermenu_contents_list"><a href="{% url 'blog:account_detail' user.pk %}">アカウント管理</a></li>
									<li class="humbergermenu_contents_list"><a href="#">ヘルプ</a></li>
									<li class="humbergermenu_contents_list"><a href="{% url 'blog:logout' %}">ログアウト</a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		{% else %}
			<div class="col-5 offset-3 mt-3">
				<div class="container">
					<div class="row">
						<div class="menu_wrap col-8">
							<form method="get" action="{% url 'blog:search_result' %}" class="post_search_form">
								{% for field in post_search_form %}
									{{ field }}
								{% endfor %}
								<button type="submit" class="post_search_button"><i class="fas fa-search"></i></button>
							</form>
						</div>
						<div class="col-4">
							<div class="container">
								<div class="row">
									<ul>
										<li class="col-6 menu_list"><a href="{% url 'blog:login' %}">Login</a></li>
										<li class="col-6 menu_list"><a href="{% url 'blog:signup' %}">Signup</a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		{% endif %}
	</div>
</header>

templates/include/modal.html
<!-- 記事削除確認画面 START　-->
<div class="modal fade" id="delete_confirm" tabindex="-1" role="dialog" aria-labelledby="label1" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">記事を削除しますか?</h5>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary"　data-dismiss="modal" id='delete_btn'>OK</button>
      </div>
    </div>
  </div>
</div>
<!-- 記事削除確認画面 END　-->


<!-- アカウント情報一括変更 START　-->
<div class="modal fade" id="update_confirm" tabindex="-1" role="dialog" aria-labelledby="label1" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">アカウント情報を一括更新しますか?</h5>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary"　data-dismiss="modal" id='update_acount_all_btn'>OK</button>
      </div>
    </div>
  </div>
</div>
<!-- アカウント情報一括変更 END　-->

<!-- コメント詳細画面 START　-->
<div class="modal fade" id="detail_comment" tabindex="-1" role="dialog" aria-labelledby="label1" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h5 class="modal-title">コメント詳細</h5>
      </div>

      <div class="modal-body container-fluid">
          <div class="row">
              <p class="col-2">Name</p>
              <p class="detail_comment_name col-10"></p>
          </div>
          <div class="row">
              <p class="col-2">Text</p>
              <p class="detail_comment_text col-10"></p>
          </div>
          <div class="row">
              <p class="col-2">Email</p>
              <p class="detail_comment_email col-10"></p>
          </div>
          <div class="row">
              <p class="col-2">Date</p>
              <p class="detail_comment_created_at col-10"></p>
          </div>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>
<!-- コメント詳細画面 END　-->


<!-- ブログ情報一括変更 START　-->
<div class="modal fade" id="update_blog_confirm" tabindex="-1" role="dialog" aria-labelledby="label1" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">ブログ情報を一括更新しますか?</h5>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary"　data-dismiss="modal" id='update_blog_all_info_btn'>OK</button>
      </div>
    </div>
  </div>
</div>
<!-- ブログ情報一括変更 END　-->