blog/urls.py
from django.urls import path, register_converter
from . import views

app_name = 'blog'

urlpatterns = [

    path('', views.IndexView.as_view(), name='index'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('signup_done/', views.SignupDoneView.as_view(), name='signup_done'),
    path('signup_complete/<token>/', views.SignupCompleteView.as_view(), name='signup_complete'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('mypage/', views.MyPageView.as_view(), name='mypage'),
    path('mypage/create_post/', views.CreatePostView.as_view(), name='create_post'),
    # path('mypage/create_post_test/', views.CreatePostTestView.as_view(), name='create_post_test'),
    path('mypage/account_detail/<int:pk>/', views.AccountDetailView.as_view(), name='account_detail'),
    path('mypage/update_account/<int:pk>/', views.UpdateAccountView.as_view(), name='update_account'),
    path('mypage/blog_management/<int:pk>/', views.BlogManagementView.as_view(), name='blog_management'),
    path('mypage/blog_management/<int:pk>/update_blog_title/', views.UpdateBlogTitleView.as_view(), name='update_blog_title'),
    path('mypage/blog_management/<int:pk>/update_blog_url/', views.UpdateBlogUrlView.as_view(), name='update_blog_url'),
    path('mypage/blog_management/<int:pk>/update_blog_info_all/', views.UpdateBlogInfoAllView.as_view(), name='update_blog_info_all'),
    path('comment_post/', views.CommentPostView.as_view(), name='comment_post'),
    path('search/', views.SearchResultView.as_view(), name='search_result'),
    path('mypage/create_post/add_tag/', views.AddTagView.as_view(), name='add_tag'),
    path('mypage/create_post/add_category/', views.AddCategoryView.as_view(), name='add_category'),
    path('mypage/account_detail/<int:pk>/update_account_all/', views.UpdateAccountAllView.as_view(), name='update_account_all'),
    path('mypage/account_detail/<int:pk>/update_username/', views.UpdateUsernameView.as_view(), name='update_username'),
    path('mypage/account_detail/<int:pk>/update_email/', views.UpdateEmailView.as_view(), name='update_email'),
    path('mypage/account_detail/<int:pk>/update_password/', views.UpdatePasswordView.as_view(), name='update_password'),
    path('mypage/edit_contents_list/', views.EditContentsListView.as_view(), name='edit_contents_list'),
    path('mypage/edit_content/<str:pk>/', views.EditContentView.as_view(),name='edit_content'),
    path('mypage/edit_content/<str:pk>/add_category/', views.AddCategoryView.as_view(),name='add_category'),
    path('mypage/edit_content/<str:pk>/add_tag/', views.AddTagView.as_view(),name='add_tag'),
    path('mypage/edit_contents_list/delete_content/', views.DeleteContentView.as_view(),name='delete_content'),
    path('mypage/comments_list/', views.CommentsListView.as_view(),name='comments_list'),
    path('mypage/comments_list/update_comments_list/', views.UpdateCommentsListView.as_view(),name='update_comments_list'),
    path('mypage/design_customize/', views.DesignCustomizeView.as_view(),name='design_customize'),
    path('mypage/access_analytics/', views.AccessAnalyticsView.as_view(), name='access_analytics'),
    # path('cotegory_list/(?P<category>\w+)/', views.CategoryListView.as_view(), name='category_list'),
    path('cotegory_list/<str>/', views.CategoryListView.as_view(), name='category_list'),
    path('tags_list/<str>/', views.TagsListView.as_view(), name='tags_list'),
]

coopy/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('', include('userblog.urls')),
    # path('markdownx/', include('markdownx.urls') ),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.core.mail import send_mail
from django.urls import reverse
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
import os, uuid, logging

# from markdownx.models import MarkdownxField
# from markdownx.utils import markdownify

logger = logging.getLogger(__name__)

class UserManager(BaseUserManager):

    use_in_migrations = True

    def _create_user(self, username, email, password, **extra_fields):

        """Create and save a user with the given username, email, and
        password."""
        if not username:
            raise ValueError('ユーザーネームは必須項目です。')

        email = self.normalize_email(email)
        username = self.model.normalize_username(username)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)


        blog_title = user.username + "'s blog"

        Blog.objects.create(
            title=blog_title,
            user=user,
            # temp_no='1',
            # temp_path='css/designTemplateCss/thema-1.css',
            url=user.username,
        )

        return user

    def create_user(self, username, email, password=None, **extra_fields):

        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, email, password, **extra_fields)

    def create_superuser(self, username, email=None, password=None, **extra_fields):

        logger.info(username)
        logger.info(email)
        logger.info(password)

        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(username, email, password, **extra_fields)


class MyUser(AbstractBaseUser, PermissionsMixin):
    """カスタムユーザーモデル."""

    username = models.CharField(_('Username'), max_length=30, unique=True)
    email = models.EmailField(_('Email'), unique=True)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )

    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )

    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def __str__(self):
        return self.username

    def get_username(self):
        return self.username

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)


def _get_latest_post(request):
    return queryset.filter(is_public=True).order_by('created_at')[:5]


class Blog(models.Model):

    title = models.CharField(_('Blog Title'), max_length=50, blank=True, null=True)
    user = models.OneToOneField(MyUser, on_delete=models.CASCADE, primary_key=True)
    url = models.SlugField(_('Url'))
    icon = models.ImageField(_('Icon'), upload_to="upload/")
    temp_no = models.CharField(max_length=20, blank=True, null=True, default='1')
    temp_path = models.CharField(max_length=255, blank=True, null=True, default='css/designTemplateCss/thema-1.css')
    created_at = models.DateTimeField(_('Created at'), auto_now_add=True)
    updated_at = models.DateTimeField(_('Updated at'), auto_now=True)

    def __str__(self):
        return "%s's blog" % self.user.username if self.title == None else self.title


class Category(models.Model):

    name = models.CharField(_('Category'), max_length=50, default='未分類')
    created_by = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    description = models.TextField(_('Description'), blank=True)
    created_at = models.DateTimeField(_('Created at'), auto_now_add=True)
    slug = models.SlugField(default=name)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = _('Categories')

    def get_latest_post(self):
        queryset = Post.objects.filter(category=self)
        return _get_latest_post(queryset)


class Tag(models.Model):

    name = models.CharField(_('Tag'), max_length=50)
    created_by = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    description = models.TextField(_('Description'), blank=True)
    created_at = models.DateTimeField(_('Created at'), auto_now_add=True)
    slug = models.SlugField(default=name)

    def __str__(self):
        return self.name

    def get_latest_post(self):
        queryset = Post.objects.filter(tag=self)
        return _get_latest_post(queryset)


def content_file_name(instance, filename):
    return 'upload/{0}/{1}/{2}'.format(instance.author, instance.title, filename)


class Post(models.Model):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=True)
    # author = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    title = models.CharField(_('Title'), max_length=255)
    content = models.TextField(_('Content'), blank=True, null=True)
    # content = MarkdownxField('Contents', help_text='markdown形式')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    # category = models.ManyToManyField(Category, blank=True)
    tags = models.ManyToManyField(Tag, blank=True)
    # thumbnail = models.FileField('Thumbnail', upload_to=content_file_name, blank=True, null=True)
    thumbnail = models.ImageField(_('Thumbnail'), upload_to="upload/", blank=True, null=True)
    created_at = models.DateTimeField(_('Created at'), auto_now_add=True)
    updated_at = models.DateTimeField(_('Updated at'), auto_now=True)
    isPublic = models.BooleanField(_('Publish or Not'), default=False)
    related_articles = models.ManyToManyField('self', blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:index')

    def formatted_markdown(self):
        return markdownify(self.content)


class Comment(models.Model):

    name = models.CharField(max_length=255, blank=True, null=True)
    text = models.TextField(_('Text'))
    email = models.EmailField(_('Email'), max_length=255, blank=True)
    target = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(_('Created at'), auto_now_add=True)
    is_public = models.BooleanField(_('Publish or Not'), default=False)

    def __str__(self):
        return self.name


class AccessAnalytics(models.Model):

    blog_pk = models.PositiveIntegerField(_('Blog Pk'), null=True, blank=True)
    blog_name = models.CharField(_('Blog Name'), max_length=50, null=True, blank=True)
    blog_owner = models.CharField(_('Blog Owner'), max_length=30, null=True, blank=True)
    blog_url = models.URLField(_('Blog Url'), null=True, blank=True)
    total_pv = models.PositiveIntegerField(_('Total PV'), null=True, blank=True)
    month_pv = models.PositiveIntegerField(_('Monthly PV'), null=True, blank=True)
    week_pv = models.PositiveIntegerField(_('Weekly PV'), null=True, blank=True)
    day_pv = models.PositiveIntegerField(_('Daily PV'), null=True, blank=True)
    total_user = models.PositiveIntegerField(_('Total User'), null=True, blank=True)
    month_user = models.PositiveIntegerField(_('Monthly User'), null=True, blank=True)
    week_user = models.PositiveIntegerField(_('Weekly User'), null=True, blank=True)
    day_user = models.PositiveIntegerField(_('Daily User'), null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.blog_name


class AccessLog(models.Model):

    blog_pk = models.PositiveIntegerField(_('Blog Pk'))
    blog_name = models.CharField(_('Blog Title'), max_length=50)
    blog_owner = models.CharField(_('Blog Owner'), max_length=30)
    blog_url = models.URLField(_('Blog Url'))
    uuId = models.UUIDField(_('Uuid'), editable=False)
    ip = models.GenericIPAddressField(_('IP Address'), unpack_ipv4=True)
    page = models.URLField(_('Page'), max_length=300)
    user = models.CharField(_('User'), max_length=30)
    timezone = models.CharField(_('Timezone'), max_length=30)
    language = models.CharField(_('Language'), max_length=30)
    device = models.CharField(_('Device'), max_length=50)
    now = models.CharField(_('Now'), max_length=30)
    referer = models.CharField(_('Referer'), max_length=300, null=True, blank=True)
    browser = models.CharField(_('Browser'), max_length=50)

    def __str__(self):
        return self.blog_name

templates/blog/access_analytics.html
{% load static %}

<div class="access_analytics_wrap container-fluid h-100">
    <div class="access_analytics_header row h-100">
        <div class="access_analytics_main col-10 h-100">
            <div class="access_analytics_main_area row h-100">
                <div class="access_analytics_main_data col-12">
                    <div class="access_analytics_main_header_area row h-100">
                        <div class="col-4">
                            <section class="access_analytics_access_value">
                                <p>アクセス数</p>
                                <i class="fas fa-desktop fa-2x access_analytics_icon_color_green"></i>
                                {% if isAccess %}
                                <span>{{ week_pv }}</span>
                                {% else %}
                                <span>0</span>
                                {% endif %}
                            </section>
                        </div>
                        <div class="col-4">
                            <section class="access_analytics_user_value">
                                <p>ユーザー数</p>
                                <i class="fas fa-users fa-2x access_analytics_icon_color_blue"></i>
                                {% if isAccess %}
                                <span>{{ week_user }}</span>
                                {% else %}
                                <span>0</span>
                                {% endif %}
                            </section>
                        </div>
                        <div class="col-4">
                            <section class="access_analytics_device_value">
                                <p>デバイス</p>
                                <i class="fas fa-mobile-alt fa-2x access_analytics_icon_color_red"></i>
                                {% if isAccess %}
                                <span>{{ day_device }}</span>
                                {% else %}
                                <span>0</span>
                                {% endif %}
                            </section>
                        </div>
                    </div>
                </div>
                {% if isAccess %}
                    <div class="access_analytics_main_image col-12">
                        <img src="{% static pv_img_week %}">
                    </div>
                    <div class="access_analytics_sub_image col-12">
                        <div class="access_analytics_sub_image_area row h-100">
                            <div class="access_analytics_sub_image_one col-6">
                                <img src="{% static pv_img_week_bar %}">
                            </div>
                            <div class="access_analytics_sub_image_two col-6">
                                <img src="{% static user_img_week_bar %}">
                            </div>
                        </div>
                    </div>
                {% else %}
                <div class="access_analytics_main_image col-12">
                    <img src="{% static pv_img_week %}">
                </div>
                {% endif %}
            </div>
        </div>
        <div class="access_analytics_sidebar col-2 h-auto">
            <ul class="access_analytics_sidebar_ul">
                <a href=""><li>アクセス数</li></a>
                <a href=""><li>ユーザー数</li></a>
                <a href=""><li>アクセスページ</li></a>
                <a href=""><li>リンク元</li></a>
                <a href=""><li>デバイス</li></a>
                <a href=""><li>ブラウザ</li></a>
                <a href=""><li>時間帯</li></a>
                <a href=""><li>地域</li></a>
            </ul>
        </div>
    </div>
</div>

templates/blog/blog_management.html
{% load static %}

{% include 'include/modal.html' %}

<p>ブログ管理画面</p>

<p class="update_blog_success_msg"></p>
<form method="post" id="update_username_form">
    {% csrf_token %}

    <p>{{ form.title.label }}</p>
    <p>{{ form.title }}</p>
    <p class="error_msg update_blog_title_error_msg"></p>
    <p><button id="update_blog_title_btn">更新する</button></p>

    <p>{{ form.url.label }}</p>
    <p>{{ form.url }}</p>
    <p class="error_msg update_blog_url_error_msg"></p>
    <p><button id="update_blog_url_btn">更新する</button></p>

    <p><button id="update_blog_all_btn">一括更新する</button></p>
    <p class="error_msg update_blog_info_all_error_msg"></p>
</form>

<p><a href="{% url 'blog:index' %}">TOPへ</a></p>

templates/blog/category_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{% endblock %}

{% block header %}
	{% include 'include/header.html' %}
{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-12 text-left mt-5">
			<h2>カテゴリー:{{ category_name }}</h2>
		</div>
	</div>

	<ul class="mt-3">
		{% for post in posts_list %}
		<li class="row search_result_wrap">
			<div class="col-4 search_thumbnail_wrap">
				{% if post.thumbnail %}
					<a href="/{{ post.blog.url }}/entry/{{ post.pk }}"><img src="{{ post.thumbnail.url }}" alt="{{ post.title }}"></a>
				{% else %}
					<a href="/{{ post.blog.url }}/entry/{{ post.pk }}"><img src="{% static 'img/light1.png' %}" alt="{{ post.title }}"></a>
				{% endif %}
			</div>
			<div class="col-8">
				<h3 class="search_title"><a href="/{{ post.blog.url }}/entry/{{ post.pk }}">{{ post.title | safe | truncatechars:22 }}</a></h3>
				<p class="search_content">{{ post.content | safe | truncatechars:60 }}</p>
			</div>
		</li>

		{% empty %}
			<p>該当する記事が存在しません。</p>
		{% endfor %}
	</ul>
</div>
{% endblock %}

<!-- ページネーション STRAT -->
{% block paginate %}
    <div class="pagination_wrap mt-5">
        {% include 'pagination.html' %}
    </div>
{% endblock %}
<!-- ページネーション END -->

templates/blog/create_post_test.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
    {% include  'include/header.html' %}
{% endblock %}

{% block content %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>{{ form.title }}</p>
    <p>{{ form.content }}</p>

    <p>{{ form.category }}</p>

    <p>{{ form.tags }}</p>

    <p>{{ form.thumbnail }}</p>
    <p>{{ form.isPublic }}</p>
    <input type="submit">
</form>
{% endblock %}

templates/blog/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
	{{ detail.title }}
{% endblock %}

{% block header %}
    {% include 'include/header.html' %}
{% endblock%}

{% block content %}
	<div class="detail_contents_wrap">
		<div class="detail_title mb-2">
			<p>{{ detail.title }}</p>
		</div>

		<div class="detail_category_wrap">
			<a href="{% url 'blog:category_list' detail.category.name %}"><p class="detail_category">{{ detail.category.name }}</p></a>
		</div>

		<div class="detail_tag_wrap">
			{% for tag in detail.tags.all %}
				<i class="fas fa-tag pr-1"></i><a href="{% url 'blog:tags_list' tag.name %}"><p class="detail_tag">{{ tag.name }}</p></a>
			{% endfor %}
		</div>

		<div class="detail_contributor_wrap">
			<p class="detail_contributor"><i class="fas fa-user pr-1"></i><a href="/{{ detail.blog.url }}/">{{ detail.blog.user }}</a></p>
		</div>


		<div class="detail_thumbnail_wrap mt-2">
			<!-- サムネの有無確認 -->
			{% if detail.thumbnail %}
				<img src="{{ detail.thumbnail.url }}" alt="{{ detal.title }}">
			{% else %}
				<img src="{% static 'img/light1.png' %}" alt="thumbnail_none">
			{% endif %}
		</div>

		<div class="detail_text_wrap mt-5">
			<p class="detail_content">{{ detail.content }}</p>
		</div>

		<h3 class="mt-5">この記事へのコメント</h3>
		<div class="detail_comments_list_wrap container mt-3 p-3">
			{% for comment in detail.comment_set.all %}
				{% if comment.is_public %}
					<div class="comment_group mt-3 mb-3 p-3">
						<p class="posted_comment_name"><strong>{{ comment.name }}</strong></p>
						<p class="posted_comment_text mt-1">{{ comment.text }}</p>
						<p class="posted_comment_dates mt-1 text-right">{{ comment.created_at | date:"Y/m/d H:i "}}</p>
					</div>
				{% endif %}
			{% empty %}
				<p>コメントがありません</p>
			{% endfor %}
		</div>

		{% if user.is_authenticated %}
		<h3 class="mt-5">コメント投稿</h3>
		<section class="comment_form_wrap mt-2 pb-3">
			<form class="container posted_comment_form" method="post">
				{% csrf_token %}
				{{ form.non_field_error }}
				{% for field in form %}
					<label for="{{ field.id_for_label }}">{{ field.tag }}</label>
					<p>{{ field }}</p>
					<p>{{ field.error }}</p>
				{% endfor %}
				<div class="text-right mt-3">
					<button type="submit" class="comment_submit btn btn-info">送信</button>
				</div>
			</form>
		</section>
		{% endif %}

	</div>
{% endblock %}

templates/blog/edit_content.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
    {% include  'include/header.html' %}
{% endblock %}

{% block content %}

<div class="container-fluid create_post_form">
    <div class="row">
        <div class="create_post_content col-9 col-xl-10">
            <p>{{ form.title }}</p>
            <p>{{ form.content }}</p>
        </div>

        <div class="col-3 col-xl-2 create_post_sidebar">
            <form method="post" id="post_form" enctype="multipart/form-data" >
                {% csrf_token %}
                <p>
                    <button type="submit" name="draft_btn" value="draft_post" class="btn btn-block btn-dark">下書き保存</button>
                </p>
                <p>
                    <button type="submit" name="update_content_btn" value="update_content" class="btn btn-block btn-success">投稿する</button>
                </p>
            </form>

            <p>カテゴリー{{ form.category }}</p>
            <form method="post" id="add_category_form">
                {% csrf_token %}
                <input type="text" name="text" id="add_category" placeholder="カテゴリー追加">
                <button type="submit" id="add_category_btn" name="add_category_btn" value="add_category" class="btn btn-dark"><i class="fas fa-plus"></i></button>
                <p class="add_category_success_msg"></p>
                <p class="error_msg add_category_error_msg"></p>
            </form>

            <p>タグ{{ form.tags }}</p>
            <form method="post" id="add_tag_form">
                {% csrf_token %}
                <input type="text" name="text" id="add_tag" placeholder="タグ追加">
                <button type="submit" id="add_tag_btn" name="add_tag_btn" value="add_tag" class="btn btn-dark"><i class="fas fa-plus"></i></button>
                <p class="add_tag_success_msg"></p>
                <p class="error_msg add_tag_error_msg"></p>
            </form>

            <p>サムネイルアップロード
                <img id='file_preview' src="{{ post.thumbnail }}" width='100%' alt="">
                <label id="id_thumbnail_wrap" class="btn btn-dark" for="id_thumbnail">
                    ファイルを選択
                    {{ form.thumbnail }}
                </label>
            </p>
            <form method="post" id="add_thumbnail_form">
                {% csrf_token %}
            </form>


        </div>
    </div>

    <div class="row">
        <div class="col-12 text-center mt-3">
            <a href="{% url 'blog:index' %}" class="btn btn-danger">CLOSE</a>
        </div>
    </div>
</div>

{% endblock %}

templates/blog/edit_contents_list.html
{% load static %}

{% include 'include/modal.html' %}

<div class="container-fluid">
	<div class="row mb-2">
		<div class="col-12">
			<h3>記事の管理</h3>
		</div>
	</div>

	<div class="row mb-2">
		<ul class="col-12 edit_contents_nav">
			<li class="col-4">記事タイトル</li>
			<li class="col-3">カテゴリー</li>
			<li class="col-2">タグ</li>
			<li class="col-1">投稿日時</li>
			<li class="col-1">編集</li>
			<li class="col-1">削除</li>
		</ul>
	</div>

		<ul class="col-12 edit_contents_list_wrap">
			{% for post in posts_list %}
			<div class="row p-1 edit_contents" content_pk="{{ post.pk }}">
				<li class="col-4"><a class="" href="/{{ post.blog.url }}/entry/{{ post.pk }}">{{ post.title | safe | truncatechars:30 }}</a></li>
				<li class="col-3">{{ post.category.name }}</li>
				<li class="col-2">
				{% for tag in post.tags.all %}
					{{ tag }}
				{% endfor %}
				</li>
				<li class="col-1">{{ post.updated_at | date:"Y/m/d" }}</li>

				<li class="col-1" style="justify-content:center;"><a class="btn btn-dark edit_btn" href="{% url 'blog:edit_content' post.pk %}">編集</a></li>
				<li class="col-1" style="justify-content:center;"><button class="btn btn-danger delete_confirm_btn" data-target="#delete_confirm" value="{{ post.pk }}">削除</button></li>
			</div>
			{% endfor %}
		</ul>
</div>

<!-- ページネーション STRAT -->
{% block paginate %}
    <div class="pagination_wrap mt-5">
        {% include 'pagination.html' %}
    </div>
{% endblock %}
<!-- ページネーション END -->

templates/blog/mypage.html
{% extends 'base.html' %}
{% load static %}

{% block headTag%}
	<link href="{% static blog.temp_path %}" rel="stylesheet" id="togleDesignTemplate">
{% endblock %}

{% block header %}
	{% include 'include/header-3.html' %}
{% endblock %}

{% block content %}
<!-- Mypage Contents START -->
<div class="container-fluid">
	<div class="row mypage_content_wrap">
		<div class="mypage_side_menu col-2">
			<p class="to_myblog"><a href="/{{ blog.url }}/">自分のサイトへ</a></p>
			<p><a href="{% url 'blog:create_post' %}">新規記事</a></p>
			<p><a href="{% url 'blog:edit_contents_list' %}">記事管理</a></p>
			<p><a href="{% url 'blog:comments_list' %}">コメント</a></p>
			<p><a href="{% url 'blog:design_customize' %}">デザインカスタマイズ</a></p>
			<p><a href="{% url 'blog:access_analytics' %}">アクセス解析</a></p>
			<p><a href="{% url 'blog:blog_management' user.pk %}">設定</a></p>
			<p><a href="{% url 'blog:account_detail' user.pk %}">アカウント管理</a></p>
			<p><a href="{% url 'blog:index' %}">TOPへ</a></p>
		</div>
		<div class="mypage_content col-10">

			{% url "blog:mypage" as mypage %}
			{% ifequal request.path mypage%}
				<p>MyPage Top</p>
			{% endifequal %}

			{% url "blog:edit_contents_list"　as edit_contents_list %}
			{% ifequal request.path edit_contents_list %}
				{% include 'blog/edit_contents_list.html' %}
			{% endifequal %}

			{% url "blog:comments_list"　as comments_list %}
			{% ifequal request.path comments_list %}
				{% include 'blog/comments_list.html' %}
			{% endifequal %}

			{% url "blog:design_customize"　as design_customize %}
			{% ifequal request.path design_customize %}
				{% include 'blog/design_customize.html' %}
			{% endifequal %}

			{% url "blog:blog_management"　user.pk as blog_management %}
			{% ifequal request.path blog_management %}
				{% include 'blog/blog_management.html' %}
			{% endifequal %}

			{% url "blog:access_analytics" as access_analytics %}
			{% ifequal request.path access_analytics %}
				{% include 'blog/access_analytics.html' %}
			{% endifequal %}

			{% url "blog:account_detail" user.pk as account_detail %}
			{% ifequal request.path account_detail %}
				{% include 'register/account_detail.html' %}
			{% endifequal %}

		</div>
	</div>
</div>
<!-- Mypage Contents END -->
{% endblock %}